# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "379ad0c5fe46c093104a6a8f3477436f"
name = "Melch.Cloud"
application_url = "https://melch.cloud/api/shopify/install"
embedded = false

[webhooks]
api_version = "2026-04"

  [[webhooks.subscriptions]]
  compliance_topics = [ "customers/data_request", "customers/redact", "shop/redact" ]
  uri = "https://melch.cloud/api/shopify/webhooks/compliance"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "https://melch.cloud/api/shopify/webhooks/app-uninstalled"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_customers,read_price_rules,read_discounts,read_fulfillments,read_inventory,read_locations,read_marketing_events,read_orders,read_products,read_returns"
optional_scopes = [ ]
use_legacy_install_flow = false

[auth]
redirect_urls = [ "https://melch.cloud/api/shopify/callback" ]
